### ISSUE TITLE
List of resources for the reverse engineering of Hi-Octane

### ISSUE THREAD

**Issue by neuromancer** [jopadan/hioctane#2]
This issue compiles a list of links with reversing information of the hi-octane game:

* https://github.com/movAX13h/HiOctaneTools
* https://moddingwiki.shikadi.net/wiki/Hi_Octane
* [Debug symbols from the PSX release](https://github.com/RetroReversing/retroReversing/blob/779ab5297c1e5501a4e563e801dfd0724acc1536/pages/ps1/PS1Symbols.md?plain=1#L59) 

Hope this brings some new information!

**Comment by jopadan** [comment]
Thanks these are the most prominent resources about the game.
